package ;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PERSON.
 */
public class Person {

    private Long id;
    private String name;
    private Integer pilotPts;
    private Integer fighterPts;
    private Integer traderPts;
    private Integer engineerPts;

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Person(Long id, String name, Integer pilotPts, Integer fighterPts, Integer traderPts, Integer engineerPts) {
        this.id = id;
        this.name = name;
        this.pilotPts = pilotPts;
        this.fighterPts = fighterPts;
        this.traderPts = traderPts;
        this.engineerPts = engineerPts;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPilotPts() {
        return pilotPts;
    }

    public void setPilotPts(Integer pilotPts) {
        this.pilotPts = pilotPts;
    }

    public Integer getFighterPts() {
        return fighterPts;
    }

    public void setFighterPts(Integer fighterPts) {
        this.fighterPts = fighterPts;
    }

    public Integer getTraderPts() {
        return traderPts;
    }

    public void setTraderPts(Integer traderPts) {
        this.traderPts = traderPts;
    }

    public Integer getEngineerPts() {
        return engineerPts;
    }

    public void setEngineerPts(Integer engineerPts) {
        this.engineerPts = engineerPts;
    }

}
