package ;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHIP.
 */
public class Ship {

    private Long id;
    private String type;
    private Integer hullStrength;
    private Integer currentCargoHold;
    private String cargo;
    private Integer fuel;
    private String weapons;
    private String shields;
    private String gadgets;

    public Ship() {
    }

    public Ship(Long id) {
        this.id = id;
    }

    public Ship(Long id, String type, Integer hullStrength, Integer currentCargoHold, String cargo, Integer fuel, String weapons, String shields, String gadgets) {
        this.id = id;
        this.type = type;
        this.hullStrength = hullStrength;
        this.currentCargoHold = currentCargoHold;
        this.cargo = cargo;
        this.fuel = fuel;
        this.weapons = weapons;
        this.shields = shields;
        this.gadgets = gadgets;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getHullStrength() {
        return hullStrength;
    }

    public void setHullStrength(Integer hullStrength) {
        this.hullStrength = hullStrength;
    }

    public Integer getCurrentCargoHold() {
        return currentCargoHold;
    }

    public void setCurrentCargoHold(Integer currentCargoHold) {
        this.currentCargoHold = currentCargoHold;
    }

    public String getCargo() {
        return cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public Integer getFuel() {
        return fuel;
    }

    public void setFuel(Integer fuel) {
        this.fuel = fuel;
    }

    public String getWeapons() {
        return weapons;
    }

    public void setWeapons(String weapons) {
        this.weapons = weapons;
    }

    public String getShields() {
        return shields;
    }

    public void setShields(String shields) {
        this.shields = shields;
    }

    public String getGadgets() {
        return gadgets;
    }

    public void setGadgets(String gadgets) {
        this.gadgets = gadgets;
    }

}
